// Maps a writeup id (slug) -> locally-downloaded official HTB machine avatar
// under /public/machines. Generated by scripts/scrape-htb-avatars.mjs.
export const machineAvatars: Record<string, string> = {
  "access": "/machines/access.png",
  "active": "/machines/active.png",
  "administrator": "/machines/administrator.png",
  "arctic": "/machines/arctic.png",
  "blackfield": "/machines/blackfield.png",
  "chatterbox": "/machines/chatterbox.png",
  "cicada": "/machines/cicada.png",
  "forest": "/machines/forest.png",
  "heist": "/machines/heist.png",
  "jeeves": "/machines/jeeves.png",
  "jerry": "/machines/jerry.png",
  "keeper": "/machines/keeper.png",
  "netmon": "/machines/netmon.png",
  "nibbles": "/machines/nibbles.png",
  "pilgrimage": "/machines/pilgrimage.png",
  "poison": "/machines/poison.png",
  "querier": "/machines/querier.png",
  "return": "/machines/return.png",
  "sauna": "/machines/sauna.png",
  "secnotes": "/machines/secnotes.png",
  "servmon": "/machines/servmon.png",
  "solidstate": "/machines/solidstate.png"
};
